name: flutter_webview_plugin_example
description: Demonstrates how to use the flutter_webview_plugin plugin.

dependencies:
  flutter:
    sdk: flutter

  package_info: ^0.4.0+10
  device_info: ^0.4.0+4
  shared_preferences: ^0.5.4+3

  url_launcher: ^3.0.2

  flutter_webview_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon_ios.png"
  image_path_android: "assets/launcher/icon_android.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/launcher/
